// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package top.jolyoulu.demo.protobuf.protobufrpc.proto;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_JolyouLu_netty_protobufrpc_proto_RPCRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_JolyouLu_netty_protobufrpc_proto_RPCRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_JolyouLu_netty_protobufrpc_proto_RPCResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_JolyouLu_netty_protobufrpc_proto_RPCResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\trpc.proto\022$top.jolyoulu.protobuf" +
      "rpc.proto\"f\n\nRPCRequest\022\n\n\002id\030\001 \001(\003\022\023\n\013s" +
      "erviceName\030\002 \001(\t\022\022\n\nmethodName\030\003 \001(\t\022\022\n\n" +
      "parameters\030\004 \001(\t\022\017\n\007version\030\005 \001(\003\"c\n\013RPC" +
      "Response\022\n\n\002id\030\001 \001(\003\022\023\n\013serviceName\030\002 \001(" +
      "\t\022\022\n\nmethodName\030\003 \001(\t\022\016\n\006result\030\004 \001(\t\022\017\n" +
      "\007version\030\005 \001(\003B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_JolyouLu_netty_protobufrpc_proto_RPCRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_JolyouLu_netty_protobufrpc_proto_RPCRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_JolyouLu_netty_protobufrpc_proto_RPCRequest_descriptor,
        new String[] { "Id", "ServiceName", "MethodName", "Parameters", "Version", });
    internal_static_com_JolyouLu_netty_protobufrpc_proto_RPCResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_JolyouLu_netty_protobufrpc_proto_RPCResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_JolyouLu_netty_protobufrpc_proto_RPCResponse_descriptor,
        new String[] { "Id", "ServiceName", "MethodName", "Result", "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
